GET https://localhost:443/auth/posts HTTP/1.1
User-Agent: REST-Client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2VybWFuIiwiaWF0IjoxNjA1NTczNTUyfQ.v9aaJNjFMPpSIbroCHkAv5T7fe7kFLHjJ-dlzFviJ38


###

POST https://localhost:443/auth/login HTTP/1.1
User-Agent: REST-Client
Content-Type: application/json

{
  "username":"German"
}
