export const Provinces = [
  'Abra',
  'Agusan del Norte',
  'Agusan del Sur',
  'Aklan',
  'Albay',
  'Antique',
  'Apayao',
  'Aurora',
  'Basilan',
  'Bataan',
  'Batanes',
  'Batangas',
  'Benguet',
  'Biliran',
  'Bohol',
  'Bukidnon',
  'Bulacan',
  'Cagayan',
  'Camarines Norte',
  'Camarines Sur',
  'Camiguin',
  'Capiz',
  'Catanduanes',
  'Cavite',
  'Cebu',
  'Cotabato',
  'Davao de Oro',
  'Davao del Sur',
  'Davao Occidental',
  'Davao Oriental',
  'Dinagat Islands',
  'Eastern Samar',
  'Guimaras',
  'Ifugao',
  'Ilocos Norte',
  'Ilocos Sur',
  'Iloilo',
  'Isabela',
  'Kalinga',
  'La Union',
  'Laguna',
  'Lanao del Norte',
  'Lanao del Sur',
  'Leyte',
  'Maguindanao',
  'Marinduque',
  'Masbate',
  'Misamis Oriental',
  'Mountain Province',
  'Negros Occidental',
  'Negros Oriental',
  'Northern Samar',
  'Nueva Vizcaya',
  'Occidental Mindoro',
  'Oriental Mindoro',
  'Palawan',
  'Pampanga',
  'Pangasinan',
  'Quezon',
  'Quirino',
  'Rizal',
  'Romblon',
  'Samar',
  'Sarangani',
  'Siquijor',
  'Sorsogon',
  'South Cotabato',
  'Southern Leyte',
  'Sultan Kudarat',
  'Sulu',
  'Surigao del Norte',
  'Surigao del Sur',
  'Tarlac',
  'Tawi-Tawi',
  'Zambales',
  'Zamboanga del Sur',
  'Zamboanga Sibugay',
  'Metro Manila',
];

export const Addresses = {
  Abra: [
    'Bangued',
    'Boliney',
    'Bucay',
    'Bucloc',
    'Daguioman',
    'Danglas',
    'Dolores',
    'La Paz',
    'Lacub',
    'Lagangilang',
    'Lagayan',
    'Langiden',
    'Licuan-Baay (Licuan)',
    'Luba',
    'Malibcong',
    'Manabo',
    'Peñarrubia',
    'Pidigan',
    'Pilar',
    'Sallapadan',
    'San Isidro',
    'San Juan',
    'San Quintin',
    'Tayum',
    'Tineg',
    'Tubo',
    'Villaviciosa',
  ],
  'Agusan del Norte': [
    'Buenavista',
    'Butuan',
    'Cabadbaran',
    'Carmen',
    'Jabonga',
    'Kitcharao',
    'Las Nieves',
    'Magallanes',
    'Nasipit',
    'Remedios T. Romualdez',
    'Santiago',
    'Tubay',
  ],
  'Agusan del Sur': [
    'Bayugan',
    'Bunawan',
    'Esperanza',
    'La Paz',
    'Loreto',
    'Prosperidad',
    'Rosario',
    'San Francisco',
    'San Luis',
    'Santa Josefa',
    'Sibagat',
    'Talacogon',
    'Trento',
    'Veruela',
  ],
  Aklan: [
    'Altavas',
    'Balete',
    'Banga',
    'Batan',
    'Buruanga',
    'Ibajay',
    'Kalibo',
    'Lezo',
    'Libacao',
    'Madalag',
    'Makato',
    'Malay',
    'Malinao',
    'Nabas',
    'New Washington',
    'Numancia',
    'Tangalan',
  ],
  Albay: [
    'Bacacay',
    'Camalig',
    'Daraga',
    'Guinobatan',
    'Jovellar',
    'Legazpi',
    'Libon',
    'Ligao',
    'Malilipot',
    'Malinao',
    'Manito',
    'Oas',
    'Pio Duran',
    'Polangui',
    'Rapu-Rapu',
    'Santo Domingo',
    'Tabaco',
    'Tiwi',
  ],
  Antique: [
    'Anini-y',
    'Barbaza',
    'Belison',
    'Bugasong',
    'Caluya',
    'Culasi',
    'Hamtic',
    'Laua-an',
    'Libertad',
    'Pandan',
    'Patnongon',
    'San Jose de Buenavista',
    'San Remigio',
    'Sebaste',
    'Sibalom',
    'Tibiao',
    'Tobias Fornier',
    'Valderrama',
  ],
  Apayao: [
    'Calanasan',
    'Conner',
    'Flora',
    'Kabugao',
    'Luna',
    'Pudtol',
    'Santa Marcela',
  ],
  Aurora: [
    'Baler',
    'Casiguran',
    'Dilasag',
    'Dinalungan',
    'Dingalan',
    'Dipaculao',
    'Maria Aurora',
    'San Luis',
  ],
  Basilan: [
    'Akbar',
    'Al-Barka',
    'Hadji Mohammad Ajul',
    'Hadji Muhtamad',
    'Isabela',
    'Lamitan',
    'Lantawan',
    'Maluso',
    'Sumisip',
    'Tabuan-Lasa',
    'Tipo-Tipo',
    'Tuburan',
    'Ungkaya Pukan',
  ],
  Bataan: [
    'Abucay',
    'Bagac',
    'Balanga',
    'Dinalupihan',
    'Hermosa',
    'Limay',
    'Mariveles',
    'Morong',
    'Orani',
    'Orion',
    'Pilar',
    'Samal',
  ],
  Batanes: ['Basco', 'Itbayat', 'Ivana', 'Mahatao', 'Sabtang', 'Uyugan'],
  Batangas: [
    'Agoncillo',
    'Alitagtag',
    'Balayan',
    'Balete',
    'Batangas City',
    'Bauan',
    'Calaca',
    'Calatagan',
    'Cuenca',
    'Ibaan',
    'Laurel',
    'Lemery',
    'Lian',
    'Lipa',
    'Lobo',
    'Mabini',
    'Malvar',
    'Mataasnakahoy',
    'Nasugbu',
    'Padre Garcia',
    'Rosario',
    'San Jose',
    'San Juan',
    'San Luis',
    'San Nicolas',
    'San Pascual',
    'Santa Teresita',
    'Santo Tomas',
    'Taal',
    'Talisay',
    'Tanauan',
    'Taysan',
    'Tingloy',
    'Tuy',
  ],
  Benguet: [
    'Atok',
    'Baguio',
    'Bakun',
    'Bokod',
    'Buguias',
    'Itogon',
    'Kabayan',
    'Kapangan',
    'Kibungan',
    'La Trinidad',
    'Mankayan',
    'Sablan',
    'Tuba',
    'Tublay',
  ],
  Biliran: [
    'Almeria',
    'Biliran',
    'Cabucgayan',
    'Caibiran',
    'Culaba',
    'Kawayan',
    'Maripipi',
    'Naval',
  ],
  Bohol: [
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Balilihan',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'Pres. Carlos P. Garcia',
    'Sagbayan',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Tagbilaran City',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ],
  Bukidnon: [
    'Baungon',
    'Cabanglasan',
    'Damulog',
    'Dangcagan',
    'Don Carlos',
    'Impasugong',
    'Kadingilan',
    'Kalilangan',
    'Kibawe',
    'Kitaotao',
    'Lantapan',
    'Libona',
    'Malaybalay',
    'Malitbog',
    'Manolo Fortich',
    'Maramag',
    'Pangantucan',
    'Quezon',
    'San Fernando',
    'Sumilao',
    'Talakag',
    'Valencia',
  ],
  Bulacan: [
    'Angat',
    'Balagtas',
    'Baliuag',
    'Bocaue',
    'Bulakan',
    'Bustos',
    'Calumpit',
    'Doña Remedios Trinidad',
    'Guiguinto',
    'Hagonoy',
    'Malolos',
    'Marilao',
    'Meycauayan',
    'Norzagaray',
    'Obando',
    'Pandi',
    'Paombong',
    'Plaridel',
    'Pulilan',
    'San Ildefonso',
    'San Jose del Monte',
    'San Miguel',
    'San Rafael',
    'Santa Maria',
  ],
  Cagayan: [],
  'Camarines Norte': [],
  'Camarines Sur': [],
  Camiguin: { cities: [] },
  Capiz: { cities: [] },
  Catanduanes: { cities: [] },
  Cavite: { cities: [] },
  Cebu: { cities: [] },
  Cotabato: { cities: [] },
  'Davao de Oro': { cities: [] },
  'Davao del Sur': { cities: [] },
  'Davao Occidental': { cities: [] },
  'Davao Oriental': { cities: [] },
  'Dinagat Islands': { cities: [] },
  'Eastern Samar': { cities: [] },
  Guimaras: { cities: [] },
  Ifugao: { cities: [] },
  'Ilocos Norte': { cities: [] },
  'Ilocos Sur': { cities: [] },
  Iloilo: { cities: [] },
  Isabela: { cities: [] },
  Kalinga: { cities: [] },
  'La Union': { cities: [] },
  Laguna: { cities: [] },
  'Lanao del Norte': { cities: [] },
  'Lanao del Sur': { cities: [] },
  Leyte: { cities: [] },
  Maguindanao: { cities: [] },
  Marinduque: { cities: [] },
  Masbate: { cities: [] },
  'Misamis Oriental': { cities: [] },
  'Mountain Province': { cities: [] },
  'Negros Occidental': { cities: [] },
  'Negros Oriental': { cities: [] },
  'Northern Samar': { cities: [] },
  'Nueva Vizcaya': { cities: [] },
  'Occidental Mindoro': { cities: [] },
  'Oriental Mindoro': { cities: [] },
  Palawan: { cities: [] },
  Pampanga: { cities: [] },
  Pangasinan: { cities: [] },
  Quezon: { cities: [] },
  Quirino: { cities: [] },
  Rizal: { cities: [] },
  Romblon: { cities: [] },
  Samar: { cities: [] },
  Sarangani: { cities: [] },
  Siquijor: { cities: [] },
  Sorsogon: { cities: [] },
  'South Cotabato': { cities: [] },
  'Southern Leyte': { cities: [] },
  'Sultan Kudarat': { cities: [] },
  Sulu: { cities: [] },
  'Surigao del Norte': { cities: [] },
  'Surigao del Sur': { cities: [] },
  Tarlac: { cities: [] },
  'Tawi-Tawi': { cities: [] },
  Zambales: { cities: [] },
  'Zamboanga del Sur': { cities: [] },
  'Zamboanga Sibugay': { cities: [] },
  'Metro Manila': { cities: [] },
};
