const QUESTION_OBJ = [
  {
    id: 1,
    dependent: { parent: undefined, who: undefined },
    type: 'select',
    name: 'property',
    question: 'What is the property that you will market ?',
    answers: [
      'Residential Lot',
      'Commercial Lot',
      'House and Lot',
      'Appartment',
      'Hotel',
      'Condominium',
      'Commercial Space',
    ],
  },
  {
    id: 2,
    dependent: { parent: 1, who: 'answers' },
    type: 'select',
    name: 'marketing',
    question: 'How are you going to market your property ?',
    answers: [],
    choice: {
      category1: [
        'My property is for sale',
        'My property is for rent',
        'This is a foreclosed property',
      ],
      category2: ['My property is for sale', 'My property is for rent'],
      category3: ['My property is for rent'],
    },
    category: {
      category1: [
        'Residential Lot',
        'Commercial Lot',
        'House and Lot',
        'Condominium',
      ],
      category2: ['Appartment', 'Commercial Space'],
      category3: ['Hotel'],
    },
  },

  {
    id: 3,
    dependent: { parent: undefined, who: undefined },
    type: 'number',
    format: 'currency',
    name: 'price',
    question: 'How much is the price ?',
  },
  {
    id: 4,
    dependent: { parent: 1, who: 'answers' },
    type: 'select',
    name: 'status',
    question: 'What is the status of your property ?',
    answers: [],
    choice: {
      category1: [
        'Pre-selling',
        'Lot Ready to Build Home',
        'Lot Ready to Build Commercial Building',
      ],
      category2: ['Pre-selling', 'Ready For Occupancy'],
    },
    category: {
      category1: ['Residential Lot', 'Commercial Lot'],
      category2: [
        'House and Lot',
        'Appartment',
        'Hotel',
        'Condominium',
        'Commercial Space',
      ],
    },
  },
  {
    id: 5,
    dependent: { parent: 1, who: 'question' },
    type: 'radio',
    name: 'typeOfDelivery',
    question: 'Type of Delivery ?',
    answers: ['bare', 'finished', 'semi-furnished', 'fully furnised'],
    render_if: ['House and Lot'],
  },
  {
    id: 6,
    dependent: { parent: 1, who: 'question' },
    type: 'select',
    name: 'typeOfHouse',
    question: 'What is the type of your house ?',
    answers: ['Townhouse', 'Duplex', 'Bungalow', 'Single Detach'],
    render_if: ['House and Lot'],
  },
  {
    id: 7,
    dependent: { parent: 1, who: 'question' },
    type: 'number',
    name: 'buildingHeights',
    question: 'How many floors your building has ?',
    render_if: ['House and Lot', 'Appartment'],
  },
  {
    id: 8,
    dependent: { parent: 1, who: 'question' },
    type: 'number',
    format: 'meter',
    name: 'lotSize',
    question: 'What is the size of the lot ?',
    render_if: ['Residential Lot', 'Commercial Lot', 'House and Lot'],
  },
  {
    id: 9,
    dependent: { parent: 1, who: 'question' },
    type: 'number',
    name: 'bedroom',
    question: 'How many bedrooms ?',
    render_if: ['House and Lot', 'Hotel', 'Appartment', 'Condominium'],
  },
  {
    id: 10,
    dependent: { parent: 1, who: 'question' },
    type: 'number',
    name: 'bathroom',
    question: 'How many bathroom ?',
    render_if: ['House and Lot', 'Hotel', 'Appartment', 'Condominium'],
  },
  {
    id: 11,
    dependent: { parent: 1, who: 'question' },
    type: 'radio',
    name: 'parking',
    question: 'Does the unit has parking space ?',
    answers: ['Yes', 'No'],
    render_if: ['House and Lot', 'Hotel', 'Appartment', 'Condominium'],
  },
  {
    id: 12,
    dependent: { parent: 11, who: 'question' },
    type: 'radio',
    name: 'typeOfParking',
    question: 'Type of parking ?',
    answers: ['Garage', 'Common Parking Space', 'Front Yard Parking'],
    render_if: ['Yes'],
  },
  {
    id: 13,
    dependent: { parent: 1, who: 'question' },
    type: 'custom-list',
    name: 'features',
    question: 'Features',
    render_if: [
      'Residential Lot',
      'Commercial Lot',
      'House and Lot',
      'Appartment',
      'Hotel',
      'Condominium',
      'Commercial Space',
    ],
  },
  {
    id: 14,
    dependent: { parent: 1, who: 'question' },
    type: 'custom-list',
    name: 'ammenities',
    question: 'Ammenities',
    render_if: [
      'Residential Lot',
      'Commercial Lot',
      'House and Lot',
      'Appartment',
      'Hotel',
      'Condominium',
      'Commercial Space',
    ],
  },
  {
    id: 15,
    dependent: { parent: 1, who: 'question' },
    type: 'custom-input',
    name: 'address',
    question: 'Address',
    render_if: [
      'Residential Lot',
      'Commercial Lot',
      'House and Lot',
      'Appartment',
      'Hotel',
      'Condominium',
      'Commercial Space',
    ],
  },
];

export default QUESTION_OBJ;
